const PSPO_EXTRA_QUESTIONS_2_TEMPLATES = [
  {
    key: 'validate-riskiest-assumption',
    answer: 'B',
    options: [
      { id: 'A', text: 'Build the full feature first to reduce uncertainty' },
      { id: 'B', text: 'Validate the riskiest assumption with the smallest useful experiment' },
      { id: 'C', text: 'Wait until the end of the release cycle to inspect feedback' },
      { id: 'D', text: 'Ask the Scrum Master to approve the idea before learning anything' },
    ],
    feedback: 'When uncertainty is high, the Product Owner should reduce the biggest risk first. A small experiment is usually better than building a large solution too early.',
    scenarios: [
      'A healthcare booking platform is considering a new self-check-in flow. The team is unsure whether patients will actually use it.',
      'An e-commerce marketplace is considering a one-click bundle purchase flow. The team is unsure whether buyers will trust it.',
      'A logistics dashboard is considering an automated delay prediction widget. The team is unsure whether dispatchers will rely on it.',
      'A subscription learning app is considering a personalized lesson recommender. The team is unsure whether learners will follow it.',
    ],
    question: 'What should the Product Owner prefer first?',
  },
  {
    key: 'outcome-metrics',
    answer: 'A',
    options: [
      { id: 'A', text: 'A metric that reflects customer or business outcome' },
      { id: 'B', text: 'The total number of story points completed' },
      { id: 'C', text: 'The number of Scrum events held' },
      { id: 'D', text: 'The size of the Scrum Team' },
    ],
    feedback: 'Outcome metrics help determine whether the product is creating value. Output metrics alone do not show whether the product change mattered.',
    scenarios: [
      'A fintech app launched a new savings assistant and wants to know whether it improved user behavior.',
      'A retail marketplace released a faster search page and wants to know whether it improved buying behavior.',
      'An internal HR tool launched a new onboarding checklist and wants to know whether it reduced friction.',
      'A travel booking site released a new cancellation flow and wants to know whether it improved the customer experience.',
    ],
    question: 'Which measurement is most useful?',
  },
  {
    key: 'reorder-after-change',
    answer: 'C',
    options: [
      { id: 'A', text: 'Keep the current order because the backlog was already reviewed' },
      { id: 'B', text: 'Remove every item and start over from scratch' },
      { id: 'C', text: 'Reorder the Product Backlog based on the new information' },
      { id: 'D', text: 'Let Developers decide the order during the Daily Scrum' },
    ],
    feedback: 'New information should influence Product Backlog ordering. The Product Owner is accountable for adapting the backlog when priorities change.',
    scenarios: [
      'A healthcare portal learns that a regulation changed the priority of one patient-facing feature.',
      'An e-commerce business learns that a competitor launched the same feature one week earlier.',
      'A logistics platform learns that a major customer no longer needs a planned integration.',
      'A subscription app learns that user interviews changed the expected value of a planned feature.',
    ],
    question: 'What is the best next step?',
  },
  {
    key: 'release-done-increment',
    answer: 'D',
    options: [
      { id: 'A', text: 'The Increment may be released whenever the business decides it is valuable' },
      { id: 'B', text: 'The Increment must wait until the Sprint Review' },
      { id: 'C', text: 'The Increment may be released only after all Product Backlog items are finished' },
      { id: 'D', text: 'The Increment must wait until the Product Owner gives permission at the Sprint end' },
    ],
    feedback: 'A Done Increment can be released whenever it makes business sense. Scrum does not require waiting for a specific event to release.',
    scenarios: [
      'A healthcare platform has a Done improvement that can help patients right away.',
      'A retail app has a Done checkout change that could reduce cart abandonment immediately.',
      'A logistics system has a Done routing update that could help dispatch today.',
      'A learning platform has a Done recommendation change that could improve retention right now.',
    ],
    question: 'What is true about releasing it?',
  },
  {
    key: 'balance-stakeholders',
    answer: 'B',
    options: [
      { id: 'A', text: 'Choose the loudest stakeholder because that saves time' },
      { id: 'B', text: 'Balance interests and order the backlog to maximize overall product value' },
      { id: 'C', text: 'Let the Scrum Master pick the stakeholder to satisfy' },
      { id: 'D', text: 'Ignore conflicts until the product is released' },
    ],
    feedback: 'Product Owners need to balance stakeholder interests. Maximizing value usually requires careful trade-offs, not simply following the most vocal request.',
    scenarios: [
      'A healthcare product has doctors, patients, and compliance teams all asking for different improvements.',
      'An e-commerce product has merchants, buyers, and marketing all asking for different priorities.',
      'A logistics product has dispatchers, managers, and warehouse staff asking for competing changes.',
      'A learning product has learners, coaches, and content creators asking for different improvements.',
    ],
    question: 'What should the Product Owner do?',
  },
  {
    key: 'split-large-item',
    answer: 'C',
    options: [
      { id: 'A', text: 'Keep the item large until the Product Owner can estimate it better' },
      { id: 'B', text: 'Move it into the Sprint Backlog exactly as it is' },
      { id: 'C', text: 'Collaborate with Developers to split or refine it into smaller useful pieces' },
      { id: 'D', text: 'Ask stakeholders to split it during the Sprint Review' },
    ],
    feedback: 'Large items are harder to inspect and forecast. Smaller slices improve learning and make planning more useful.',
    scenarios: [
      'A healthcare team has one epic-sized feature for appointment reminders and needs to make it manageable.',
      'An e-commerce team has one giant checkout improvement and needs to make it manageable.',
      'A logistics team has one oversized warehouse optimization idea and needs to make it manageable.',
      'A learning team has one big personalization idea and needs to make it manageable.',
    ],
    question: 'What is the best next step?',
  },
  {
    key: 'product-goal',
    answer: 'A',
    options: [
      { id: 'A', text: 'A longer-term objective that aligns the Product Backlog and product decisions' },
      { id: 'B', text: 'A detailed task list for the next 24 hours' },
      { id: 'C', text: 'A replacement for the Product Backlog' },
      { id: 'D', text: 'A role assigned to one Developer' },
    ],
    feedback: 'The Product Goal gives a shared longer-term direction. It helps the Scrum Team and stakeholders understand why the product is being built.',
    scenarios: [
      'A healthcare platform wants to reduce the time patients spend waiting for care coordination.',
      'An e-commerce product wants to improve repeat purchase behavior over the next few Sprints.',
      'A logistics platform wants to reduce delivery exceptions across several releases.',
      'A learning platform wants to increase course completion over a quarter.',
    ],
    question: 'What does this best describe?',
  },
  {
    key: 'definition-of-done',
    answer: 'A',
    options: [
      { id: 'A', text: 'A shared quality standard that makes a done Increment transparent and usable' },
      { id: 'B', text: 'A list of stakeholders who approve the release' },
      { id: 'C', text: 'A backlog ordering rule based on size' },
      { id: 'D', text: 'A replacement for Sprint Planning' },
    ],
    feedback: 'The Definition of Done increases transparency around quality. It helps the Scrum Team know what is required for a usable Increment.',
    scenarios: [
      'A healthcare platform wants every increment to meet privacy and compliance expectations before release.',
      'An e-commerce product wants every increment to meet checkout quality expectations before release.',
      'A logistics system wants every increment to meet reliability expectations before release.',
      'A learning app wants every increment to meet accessibility expectations before release.',
    ],
    question: 'Which Scrum artifact is most relevant?',
  },
  {
    key: 'sprint-goal-protection',
    answer: 'B',
    options: [
      { id: 'A', text: 'Accept all changes as long as the Product Owner asks for them' },
      { id: 'B', text: 'Protect the Sprint Goal while renegotiating scope when needed' },
      { id: 'C', text: 'Cancel the Sprint whenever a new request appears' },
      { id: 'D', text: 'Freeze all communication until the Sprint ends' },
    ],
    feedback: 'During a Sprint, scope can be renegotiated as long as the Sprint Goal is not endangered. The goal provides focus.',
    scenarios: [
      'A healthcare team gets a request to add a small feature to a Sprint item already being worked on.',
      'An e-commerce team gets a request to adjust a checkout item that is currently being built.',
      'A logistics team gets a request to alter a delivery item while the Sprint is in progress.',
      'A learning team gets a request to tweak a lesson item during the Sprint.',
    ],
    question: 'What should the Developers do?',
  },
  {
    key: 'forecast-in-planning',
    answer: 'C',
    options: [
      { id: 'A', text: 'Stakeholders forecast the amount of work the team can do' },
      { id: 'B', text: 'The Scrum Master forecasts the Sprint capacity alone' },
      { id: 'C', text: 'Developers forecast how much work they believe they can complete' },
      { id: 'D', text: 'The Product Owner forecasts the team capacity and assigns it' },
    ],
    feedback: 'In Sprint Planning, Developers forecast how much work they can take on. That forecast supports the Sprint Backlog selection.',
    scenarios: [
      'A healthcare team is deciding how many patient portal items can fit into the Sprint.',
      'An e-commerce team is deciding how many checkout improvements can fit into the Sprint.',
      'A logistics team is deciding how many routing improvements can fit into the Sprint.',
      'A learning team is deciding how many lesson improvements can fit into the Sprint.',
    ],
    question: 'Who makes that forecast?',
  },
  {
    key: 'sprint-review-purpose',
    answer: 'A',
    options: [
      { id: 'A', text: 'Inspect the Increment and adapt the Product Backlog based on feedback' },
      { id: 'B', text: 'Assign every Developer new tasks for the next Sprint' },
      { id: 'C', text: 'Approve the Definition of Done for the next release only' },
      { id: 'D', text: 'Replace Product Backlog refinement for the whole product' },
    ],
    feedback: 'The Sprint Review is for inspection and adaptation. It helps the Scrum Team and stakeholders decide what to do next.',
    scenarios: [
      'A healthcare platform shows a new appointment flow to clinicians and patients.',
      'An e-commerce product shows a checkout improvement to merchants and buyers.',
      'A logistics tool shows a routing improvement to dispatchers and managers.',
      'A learning platform shows a recommendation improvement to learners and coaches.',
    ],
    question: 'What is the main purpose of the event?',
  },
  {
    key: 'ordering-factors',
    answer: 'D',
    options: [
      { id: 'A', text: 'By the number of people requesting the item' },
      { id: 'B', text: 'By the least amount of code needed' },
      { id: 'C', text: 'By the oldest item in the backlog' },
      { id: 'D', text: 'By value, risk, dependencies, and learning potential' },
    ],
    feedback: 'Product Backlog ordering is a Product Owner responsibility and should consider multiple factors that affect value and risk.',
    scenarios: [
      'A healthcare product has several candidate improvements with different risk levels and regulatory dependencies.',
      'An e-commerce product has several candidate improvements with different value and dependency patterns.',
      'A logistics product has several candidate improvements that differ in operational risk and learning value.',
      'A learning product has several candidate improvements that differ in user value and integration dependencies.',
    ],
    question: 'What is the best ordering approach?',
  },
  {
    key: 'cancel-sprint',
    answer: 'B',
    options: [
      { id: 'A', text: 'The Scrum Master can cancel the Sprint if stakeholders ask' },
      { id: 'B', text: 'Only the Product Owner can cancel the Sprint when the Sprint Goal becomes obsolete' },
      { id: 'C', text: 'Developers can cancel the Sprint whenever they dislike the plan' },
      { id: 'D', text: 'Any stakeholder can cancel the Sprint during the Daily Scrum' },
    ],
    feedback: 'Only the Product Owner may cancel the Sprint, and only when the Sprint Goal no longer makes sense.',
    scenarios: [
      'A healthcare product has a Sprint Goal that no longer matters after a regulatory change.',
      'An e-commerce product has a Sprint Goal that no longer matters after a market shift.',
      'A logistics product has a Sprint Goal that no longer matters after a major contract change.',
      'A learning product has a Sprint Goal that no longer matters after a new strategy decision.',
    ],
    question: 'Who has the authority to do this?',
  },
  {
    key: 'product-backlog-emergent',
    answer: 'C',
    options: [
      { id: 'A', text: 'The Product Backlog must never change after Sprint Planning' },
      { id: 'B', text: 'The Product Backlog is owned by stakeholders collectively' },
      { id: 'C', text: 'The Product Backlog is emergent and should adapt as learning appears' },
      { id: 'D', text: 'The Product Backlog is replaced by the Sprint Backlog every Sprint' },
    ],
    feedback: 'The Product Backlog is not frozen. It emerges and adapts as new information changes what is most valuable or risky.',
    scenarios: [
      'A healthcare platform discovers new patient behavior after a release.',
      'An e-commerce product learns new buying patterns after a promotion.',
      'A logistics product learns new delay patterns after a busy season.',
      'A learning product learns new engagement patterns after a course launch.',
    ],
    question: 'What should happen to the backlog?',
  },
  {
    key: 'release-value-timing',
    answer: 'A',
    options: [
      { id: 'A', text: 'Release timing should be driven by value and business judgment' },
      { id: 'B', text: 'Releases must happen only on the last day of the Sprint' },
      { id: 'C', text: 'Releases are forbidden until every item in the Product Backlog is complete' },
      { id: 'D', text: 'The Scrum Master decides the release calendar for the product' },
    ],
    feedback: 'Scrum does not prescribe a release cadence. A Done Increment can be released when it is valuable to do so.',
    scenarios: [
      'A healthcare product has a completed improvement that could reduce patient waiting time immediately.',
      'An e-commerce product has a completed checkout improvement that could improve conversion immediately.',
      'A logistics product has a completed route optimization that could improve delivery performance immediately.',
      'A learning product has a completed lesson tweak that could improve retention immediately.',
    ],
    question: 'What is the best answer?',
  },
  {
    key: 'refinement-purpose',
    answer: 'B',
    options: [
      { id: 'A', text: 'To assign all work items to individual Developers' },
      { id: 'B', text: 'To make upcoming Product Backlog items clearer and better prepared for selection' },
      { id: 'C', text: 'To cancel the need for Sprint Planning' },
      { id: 'D', text: 'To replace the Product Goal' },
    ],
    feedback: 'Refinement helps the Scrum Team prepare Product Backlog items so they are easier to discuss and select when needed.',
    scenarios: [
      'A healthcare team needs to prepare a new patient messaging item for a future Sprint.',
      'An e-commerce team needs to prepare a new product recommendation item for a future Sprint.',
      'A logistics team needs to prepare a new dispatch automation item for a future Sprint.',
      'A learning team needs to prepare a new content personalization item for a future Sprint.',
    ],
    question: 'What is the main purpose of that activity?',
  },
  {
    key: 'outcome-not-output',
    answer: 'A',
    options: [
      { id: 'A', text: 'Measure the change in user or business behavior the product created' },
      { id: 'B', text: 'Count the number of tasks finished by the team' },
      { id: 'C', text: 'Count the number of meetings held in the Sprint' },
      { id: 'D', text: 'Count the number of Developers who attended the review' },
    ],
    feedback: 'The Product Owner should focus on outcomes, because outputs alone do not tell whether the product actually created value.',
    scenarios: [
      'A healthcare platform wants to know whether a new triage flow improved appointment completion.',
      'An e-commerce product wants to know whether a new search filter improved order conversion.',
      'A logistics product wants to know whether a new dashboard improved dispatch decisions.',
      'A learning product wants to know whether a new reminder improved lesson completion.',
    ],
    question: 'What should be measured?',
  },
  {
    key: 'roadmap-vs-backlog',
    answer: 'B',
    options: [
      { id: 'A', text: 'A roadmap replaces the Product Backlog and makes ordering unnecessary' },
      { id: 'B', text: 'A roadmap can communicate direction, but the Product Backlog remains the ordered source of work' },
      { id: 'C', text: 'A roadmap belongs to the Scrum Master and not the Product Owner' },
      { id: 'D', text: 'A roadmap is the same thing as the Definition of Done' },
    ],
    feedback: 'A roadmap can help communicate direction, but it does not replace the Product Backlog or the Product Owner’s ordering responsibility.',
    scenarios: [
      'A healthcare product team wants to show long-term direction to hospital leadership.',
      'An e-commerce product team wants to show long-term direction to merchants and investors.',
      'A logistics product team wants to show long-term direction to operations managers.',
      'A learning product team wants to show long-term direction to content partners.',
    ],
    question: 'Which statement is best?',
  },
  {
    key: 'small-experiments',
    answer: 'C',
    options: [
      { id: 'A', text: 'Avoid experiments because they slow delivery' },
      { id: 'B', text: 'Build the entire idea before checking any assumptions' },
      { id: 'C', text: 'Use small experiments to learn quickly and reduce risk' },
      { id: 'D', text: 'Wait for one large stakeholder meeting before learning anything' },
    ],
    feedback: 'Small experiments support faster learning and lower the cost of being wrong.',
    scenarios: [
      'A healthcare product is unsure whether users will adopt a new reminder format.',
      'An e-commerce product is unsure whether shoppers will use a new comparison tool.',
      'A logistics product is unsure whether dispatchers will rely on a new planning hint.',
      'A learning product is unsure whether students will use a new study streak feature.',
    ],
    question: 'What is the best approach?',
  },
  {
    key: 'sprint-review-transparency',
    answer: 'A',
    options: [
      { id: 'A', text: 'Use the Sprint Review to make progress transparent and invite feedback' },
      { id: 'B', text: 'Use the Sprint Review to lock the next Sprint Backlog in advance' },
      { id: 'C', text: 'Use the Sprint Review to assign overtime to Developers' },
      { id: 'D', text: 'Use the Sprint Review to replace all Product Owner decisions' },
    ],
    feedback: 'Sprint Review is a transparency and feedback moment. It helps the Scrum Team inspect progress and adapt the Product Backlog.',
    scenarios: [
      'A healthcare product wants stakeholders to see progress on a new patient portal feature.',
      'An e-commerce product wants stakeholders to see progress on a checkout enhancement.',
      'A logistics product wants stakeholders to see progress on a fleet planning enhancement.',
      'A learning product wants stakeholders to see progress on a course recommendation change.',
    ],
    question: 'What is the best use of the event?',
  },
  {
    key: 'product-owner-accountability',
    answer: 'D',
    options: [
      { id: 'A', text: 'The Scrum Master is accountable for maximizing product value' },
      { id: 'B', text: 'The Developers are accountable for maximizing product value' },
      { id: 'C', text: 'Stakeholders are accountable for maximizing product value' },
      { id: 'D', text: 'The Product Owner is accountable for maximizing product value' },
    ],
    feedback: 'The Product Owner is accountable for maximizing product value. That accountability includes Product Backlog ordering and stakeholder collaboration.',
    scenarios: [
      'A healthcare team asks who should make the final call on product value trade-offs.',
      'An e-commerce team asks who should make the final call on product value trade-offs.',
      'A logistics team asks who should make the final call on product value trade-offs.',
      'A learning team asks who should make the final call on product value trade-offs.',
    ],
    question: 'Who is accountable?',
  },
  {
    key: 'product-backlog-source-of-work',
    answer: 'B',
    options: [
      { id: 'A', text: 'The Sprint Backlog becomes the only source of work after Sprint Planning' },
      { id: 'B', text: 'The Product Backlog is the single ordered source of work for the product' },
      { id: 'C', text: 'The Daily Scrum is the source of all work items' },
      { id: 'D', text: 'The Definition of Done is the source of work for the product' },
    ],
    feedback: 'The Product Backlog is the ordered list of what is needed to improve the product. It remains the product’s source of work.',
    scenarios: [
      'A healthcare platform wants one place to order future improvements.',
      'An e-commerce product wants one place to order future improvements.',
      'A logistics product wants one place to order future improvements.',
      'A learning product wants one place to order future improvements.',
    ],
    question: 'Which statement best fits Scrum?',
  },
  {
    key: 'learning-before-scaling',
    answer: 'C',
    options: [
      { id: 'A', text: 'Spend as much money as possible before gathering feedback' },
      { id: 'B', text: 'Delay learning until after the product is fully built' },
      { id: 'C', text: 'Use early learning to guide whether the idea deserves more investment' },
      { id: 'D', text: 'Let stakeholders prioritize based on opinion alone' },
    ],
    feedback: 'Learning early helps the Product Owner decide whether to continue investing, adapt, or stop.',
    scenarios: [
      'A healthcare startup is considering a new symptom-checking feature.',
      'An e-commerce company is considering a new live shopping feature.',
      'A logistics company is considering a new demand prediction feature.',
      'A learning company is considering a new AI tutor feature.',
    ],
    question: 'What is the smartest thing to do first?',
  },
  {
    key: 'product-value-feedback-loop',
    answer: 'A',
    options: [
      { id: 'A', text: 'Inspect what is happening and adapt the Product Backlog based on learning' },
      { id: 'B', text: 'Ignore feedback until the release date' },
      { id: 'C', text: 'Only follow the original plan no matter what changes' },
      { id: 'D', text: 'Ask the Scrum Master to cancel learning efforts' },
    ],
    feedback: 'Scrum is empirical. Inspection and adaptation keep the product moving toward value as conditions change.',
    scenarios: [
      'A healthcare product receives new clinical feedback after a prototype review.',
      'An e-commerce product receives new buyer feedback after a prototype review.',
      'A logistics product receives new dispatcher feedback after a prototype review.',
      'A learning product receives new learner feedback after a prototype review.',
    ],
    question: 'What should happen next?',
  },
].slice(0, 20);

window.PSPO_EXTRA_QUESTIONS_2 = PSPO_EXTRA_QUESTIONS_2_TEMPLATES.flatMap((template, templateIndex) =>
  template.scenarios.map((scenario, scenarioIndex) => ({
    id: `extra2-${String(templateIndex + 1).padStart(2, '0')}-${scenarioIndex + 1}`,
    source: 'pspo-original-2',
    sourceNumber: templateIndex * 4 + scenarioIndex + 1,
    prompt: `${scenario} ${template.question}`,
    chooseAll: false,
    options: template.options,
    answer: [template.answer],
    feedback: template.feedback,
  })),
);
